<a href="https://colab.research.google.com/github/imjyong/CS/blob/main/ml-dl-selfstudy/practice/E_commerce_transaction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **이커머스 거래/고객 행동 데이터**

- chat GPT 로 생성한 데이터
  - 동일 ID임에도 City, Address 주소가 다름

### **데이터셋**

In [ ]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# 랜덤 시드 고정
np.random.seed(42)
random.seed(42)

# 고객 수
n = 100

# 고객 ID
customer_ids = [f'C{1000+i}' for i in range(n)]

# 성별
genders = np.random.choice(['Male', 'Female'], size=n)

# 나이
ages = np.random.randint(18, 70, size=n)

# 나이대 파생
def get_age_group(age):
    if age < 20:
        return '10대'
    elif age < 30:
        return '20대'
    elif age < 40:
        return '30대'
    elif age < 50:
        return '40대'
    elif age < 60:
        return '50대'
    else:
        return '60대 이상'

age_groups = [get_age_group(age) for age in ages]

# 도시 및 국가
cities = ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Gwangju']
countries = ['South Korea'] * n
city_choices = np.random.choice(cities, size=n)

# 상품 정보
products = ['T-Shirt', 'Jeans', 'Sneakers', 'Phone', 'Laptop', 'Headphones', 'Watch', 'Backpack']
categories = {
    'T-Shirt': 'Fashion',
    'Jeans': 'Fashion',
    'Sneakers': 'Fashion',
    'Phone': 'Electronics',
    'Laptop': 'Electronics',
    'Headphones': 'Electronics',
    'Watch': 'Accessories',
    'Backpack': 'Accessories'
}
product_choices = np.random.choice(products, size=n)
product_categories = [categories[p] for p in product_choices]

# 가격
price_dict = {
    'T-Shirt': 20,
    'Jeans': 50,
    'Sneakers': 80,
    'Phone': 500,
    'Laptop': 1000,
    'Headphones': 150,
    'Watch': 200,
    'Backpack': 60
}
prices = [price_dict[p] for p in product_choices]

# 수량
quantities = np.random.randint(1, 5, size=n)

# 총 금액
total_amounts = [p * q for p, q in zip(prices, quantities)]

# 구매 일시
start_date = datetime(2023, 1, 1)
purchase_dates = [start_date + timedelta(days=int(x)) for x in np.random.randint(0, 365, size=n)]

# 결제 수단
payment_methods = np.random.choice(['Credit Card', 'KakaoPay', 'PayPal', 'Bank Transfer'], size=n)

# 장바구니에 담은 총 품목 수
cart_items = np.random.randint(1, 10, size=n)

# 쿠폰 사용 여부
used_coupon = np.random.choice([True, False], size=n)

# 데이터프레임 생성
df = pd.DataFrame({
    'CustomerID': customer_ids,
    'Gender': genders,
    'Age': ages,
    'AgeGroup': age_groups,
    'City': city_choices,
    'Country': countries,
    'Product': product_choices,
    'Category': product_categories,
    'Price': prices,
    'Quantity': quantities,
    'TotalAmount': total_amounts,
    'PurchaseDate': purchase_dates,
    'PaymentMethod': payment_methods,
    'CartItemCount': cart_items,
    'UsedCoupon': used_coupon
})

# 지역 + 도로명 + 번지수 조합
streets = ['강남대로', '테헤란로', '서초대로', '올림픽로', '광안로', '중앙로', '명동길', '송도과학로']
regions = ['서울특별시 강남구', '서울특별시 서초구', '부산광역시 해운대구', '인천광역시 연수구', '대구광역시 중구']
building_numbers = np.random.randint(1, 200, size=100)

# 주소 조합
addresses = [f"{random.choice(regions)} {random.choice(streets)} {num}" for num in building_numbers]

# 데이터프레임에 추가
df['Address'] = addresses

In [ ]:
df

,CustomerID,Gender,Age,AgeGroup,City,Country,Product,Category,Price,Quantity,TotalAmount,PurchaseDate,PaymentMethod,CartItemCount,UsedCoupon,Address
0,C1000,Male,35,30대,Incheon,South Korea,T-Shirt,Fashion,20,4,80,2023-05-30,PayPal,3,True,서울특별시 강남구 강남대로 50
1,C1001,Female,43,40대,Incheon,South Korea,Jeans,Fashion,50,1,50,2023-11-10,KakaoPay,1,True,부산광역시 해운대구 올림픽로 12
2,C1002,Male,61,60대 이상,Daegu,South Korea,T-Shirt,Fashion,20,4,80,2023-02-27,Credit Card,4,True,서울특별시 서초구 서초대로 193
3,C1003,Male,51,50대,Busan,South Korea,Backpack,Accessories,60,4,240,2023-12-08,Bank Transfer,9,True,서울특별시 강남구 테헤란로 54
4,C1004,Male,27,20대,Busan,South Korea,Headphones,Electronics,150,2,300,2023-11-01,Bank Transfer,3,True,대구광역시 중구 명동길 133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,C1095,Female,60,60대 이상,Daegu,South Korea,Sneakers,Fashion,80,1,80,2023-11-21,Bank Transfer,2,False,대구광역시 중구 올림픽로 47
96,C1096,Female,46,40대,Busan,South Korea,Phone,Electronics,500,2,1000,2023-01-04,Bank Transfer,5,False,부산광역시 해운대구 송도과학로 121
97,C1097,Female,53,50대,Seoul,South Korea,Sneakers,Fashion,80,3,240,2023-01-16,Credit Card,9,False,서울특별시 서초구 서초대로 56
98,C1098,Female,30,30대,Daegu,South Korea,Backpack,Accessories,60,2,120,2023-10-07,KakaoPay,4,True,대구광역시 중구 송도과학로 94
99,C1099,Male,49,40대,Daegu,South Korea,T-Shirt,Fashion,20,1,20,2023-12-02,Credit Card,6,True,서울특별시 서초구 송도과학로 107

### **실습 전 데이터셋 가공**

In [ ]:
df = df.drop('AgeGroup', axis=1)
df = df.drop('TotalAmount', axis=1)

In [ ]:
df.head()

,CustomerID,Gender,Age,City,Country,Product,Category,Price,Quantity,PurchaseDate,PaymentMethod,CartItemCount,UsedCoupon,Address,Age Group,Address1,Address2
0,C1000,Male,35,Incheon,South Korea,T-Shirt,Fashion,20,4,2023-05-30,PayPal,3,True,서울특별시 강남구 강남대로 50,30대,서울,수도권
1,C1001,Female,43,Incheon,South Korea,Jeans,Fashion,50,1,2023-11-10,KakaoPay,1,True,부산광역시 해운대구 올림픽로 12,40대,부산,수도권
2,C1002,Male,61,Daegu,South Korea,T-Shirt,Fashion,20,4,2023-02-27,Credit Card,4,True,서울특별시 서초구 서초대로 193,60대 이상,서울,지방
3,C1003,Male,51,Busan,South Korea,Backpack,Accessories,60,4,2023-12-08,Bank Transfer,9,True,서울특별시 강남구 테헤란로 54,50대,서울,지방
4,C1004,Male,27,Busan,South Korea,Headphones,Electronics,150,2,2023-11-01,Bank Transfer,3,True,대구광역시 중구 명동길 133,20대,대구,지방

In [ ]:
df['PurchaseDate'].info()

In [ ]:
df['PurchaseDate'] = df['PurchaseDate'].astype('int')

In [ ]:
df['PurchaseDate'].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CustomerID     100 non-null    object
 1   Gender         100 non-null    object
 2   Age            100 non-null    int64
 3   City           100 non-null    object
 4   Country        100 non-null    object
 5   Product        100 non-null    object
 6   Category       100 non-null    object
 7   Price          100 non-null    int64
 8   Quantity       100 non-null    int64
 9   PurchaseDate   100 non-null    int64
 10  PaymentMethod  100 non-null    object
 11  CartItemCount  100 non-null    int64
 12  UsedCoupon     100 non-null    bool
 13  Address        100 non-null    object
dtypes: bool(1), int64(5), object(8)
memory usage: 10.4+ KB

### **실습**

In [ ]:
df.head()

,CustomerID,Gender,Age,City,Country,Product,Category,Price,Quantity,PurchaseDate,PaymentMethod,CartItemCount,UsedCoupon,Address
0,C1000,Male,35,Incheon,South Korea,T-Shirt,Fashion,20,4,1685404800000000000,PayPal,3,True,서울특별시 강남구 강남대로 50
1,C1001,Female,43,Incheon,South Korea,Jeans,Fashion,50,1,1699574400000000000,KakaoPay,1,True,부산광역시 해운대구 올림픽로 12
2,C1002,Male,61,Daegu,South Korea,T-Shirt,Fashion,20,4,1677456000000000000,Credit Card,4,True,서울특별시 서초구 서초대로 193
3,C1003,Male,51,Busan,South Korea,Backpack,Accessories,60,4,1701993600000000000,Bank Transfer,9,True,서울특별시 강남구 테헤란로 54
4,C1004,Male,27,Busan,South Korea,Headphones,Electronics,150,2,1698796800000000000,Bank Transfer,3,True,대구광역시 중구 명동길 133

#### **1. 연령대 그룹 생성**

In [ ]:
df.head()

,CustomerID,Gender,Age,City,Country,Product,Category,Price,Quantity,PurchaseDate,PaymentMethod,CartItemCount,UsedCoupon,Address,Age Group,Address1,Address2
0,C1000,Male,35,Incheon,South Korea,T-Shirt,Fashion,20,4,2023-05-30,PayPal,3,True,서울특별시 강남구 강남대로 50,30대,서울,수도권
1,C1001,Female,43,Incheon,South Korea,Jeans,Fashion,50,1,2023-11-10,KakaoPay,1,True,부산광역시 해운대구 올림픽로 12,40대,부산,수도권
2,C1002,Male,61,Daegu,South Korea,T-Shirt,Fashion,20,4,2023-02-27,Credit Card,4,True,서울특별시 서초구 서초대로 193,60대 이상,서울,지방
3,C1003,Male,51,Busan,South Korea,Backpack,Accessories,60,4,2023-12-08,Bank Transfer,9,True,서울특별시 강남구 테헤란로 54,50대,서울,지방
4,C1004,Male,27,Busan,South Korea,Headphones,Electronics,150,2,2023-11-01,Bank Transfer,3,True,대구광역시 중구 명동길 133,20대,대구,지방

In [ ]:
df.shape

(100, 17)

In [ ]:
def age_group(age):
    if age < 10:
        return '0대'
    elif age < 20:
        return '10대'
    elif age < 30:
        return '20대'
    elif age < 40:
        return '30대'
    elif age < 50:
        return '40대'
    elif age < 60:
        return '50대'
    else:
        return '60대 이상'

df['AgeGroup'] = df['Age'].apply(age_group) # df['셀 이름 (매개변수)'].apply(함수명)

In [ ]:
df.head()

,CustomerID,Gender,Age,City,Country,Product,Category,Price,Quantity,PurchaseDate,PaymentMethod,CartItemCount,UsedCoupon,Address,Age Group,Address1,Address2
0,C1000,Male,35,Incheon,South Korea,T-Shirt,Fashion,20,4,2023-05-30,PayPal,3,True,서울특별시 강남구 강남대로 50,30대,서울,수도권
1,C1001,Female,43,Incheon,South Korea,Jeans,Fashion,50,1,2023-11-10,KakaoPay,1,True,부산광역시 해운대구 올림픽로 12,40대,부산,수도권
2,C1002,Male,61,Daegu,South Korea,T-Shirt,Fashion,20,4,2023-02-27,Credit Card,4,True,서울특별시 서초구 서초대로 193,60대 이상,서울,지방
3,C1003,Male,51,Busan,South Korea,Backpack,Accessories,60,4,2023-12-08,Bank Transfer,9,True,서울특별시 강남구 테헤란로 54,50대,서울,지방
4,C1004,Male,27,Busan,South Korea,Headphones,Electronics,150,2,2023-11-01,Bank Transfer,3,True,대구광역시 중구 명동길 133,20대,대구,지방

In [ ]:
df.shape

(100, 17)

#### **2. Address1 = 서울, 대구, 부산, 그 외 분류**

In [ ]:
df.loc[:, 'Address']

0        서울특별시 강남구 강남대로 50
1       부산광역시 해운대구 올림픽로 12
2       서울특별시 서초구 서초대로 193
3        서울특별시 강남구 테헤란로 54
4         대구광역시 중구 명동길 133
              ...
95        대구광역시 중구 올림픽로 47
96    부산광역시 해운대구 송도과학로 121
97       서울특별시 서초구 서초대로 56
98       대구광역시 중구 송도과학로 94
99     서울특별시 서초구 송도과학로 107
Name: Address, Length: 100, dtype: object

In [ ]:
def address1(address):
    address = address[:2]

    if address == '서울':
        return '서울'
    if address == '대구':
        return '대구'
    if address == '부산':
        return '부산'
    else:
        return '그 외'

df['Address1'] = df['Address'].apply(address1)

In [ ]:
df.loc[:, ['Address', 'Address1']]

                 Address Address1
0      서울특별시 강남구 강남대로 50       서울
1     부산광역시 해운대구 올림픽로 12       부산
2     서울특별시 서초구 서초대로 193       서울
3      서울특별시 강남구 테헤란로 54       서울
4       대구광역시 중구 명동길 133       대구
..                   ...      ...
95      대구광역시 중구 올림픽로 47       대구
96  부산광역시 해운대구 송도과학로 121       부산
97     서울특별시 서초구 서초대로 56       서울
98     대구광역시 중구 송도과학로 94       대구
99   서울특별시 서초구 송도과학로 107       서울

[100 rows x 2 columns]

#### **3. Address2 = 수도권 (서울, 경기도, 인천), 지방 분류**

In [ ]:
df.loc[:, 'City']

0     Incheon
1     Incheon
2       Daegu
3       Busan
4       Busan
       ...
95      Daegu
96      Busan
97      Seoul
98      Daegu
99      Daegu
Name: City, Length: 100, dtype: object

In [ ]:
def address2(city):
    if city == 'Incheon' or city == 'Seoul' or city == 'Gyeonggi-do':
        return '수도권'
    else:
        return '지방'

df['Address2'] = df['City'].apply(address2)

In [ ]:
df.loc[:, ['City', 'Address2']]

       City Address2
0   Incheon      수도권
1   Incheon      수도권
2     Daegu       지방
3     Busan       지방
4     Busan       지방
..      ...      ...
95    Daegu       지방
96    Busan       지방
97    Seoul      수도권
98    Daegu       지방
99    Daegu       지방

[100 rows x 2 columns]

#### **4. PurchaseDate = int -> datetime**

In [ ]:
df['PurchaseDate'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 100 entries, 0 to 99
Series name: PurchaseDate
Non-Null Count  Dtype
--------------  -----
100 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 932.0 bytes

In [ ]:
import pandas as pd

df['PurchaseDate'] = pd.to_datetime(df['PurchaseDate'])

In [ ]:
df['PurchaseDate'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 100 entries, 0 to 99
Series name: PurchaseDate
Non-Null Count  Dtype
--------------  -----
100 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 932.0 bytes

#### **5. PurchaseDate 년, 월, 요일**

In [ ]:
df.loc[:, 'PurchaseDate']

0    2023-05-30
1    2023-11-10
2    2023-02-27
3    2023-12-08
4    2023-11-01
        ...
95   2023-11-21
96   2023-01-04
97   2023-01-16
98   2023-10-07
99   2023-12-02
Name: PurchaseDate, Length: 100, dtype: datetime64[ns]

In [ ]:
df['Year'] = df['PurchaseDate'].dt.year
print(df['Year'])

0     2023
1     2023
2     2023
3     2023
4     2023
      ...
95    2023
96    2023
97    2023
98    2023
99    2023
Name: Year, Length: 100, dtype: int32

In [ ]:
df['Month'] = df['PurchaseDate'].dt.month
print(df['Month'])

0      5
1     11
2      2
3     12
4     11
      ..
95    11
96     1
97     1
98    10
99    12
Name: Month, Length: 100, dtype: int32

In [ ]:
df['Day'] = df['PurchaseDate'].dt.day
print(df['Day'])

0     30
1     10
2     27
3      8
4      1
      ..
95    21
96     4
97    16
98     7
99     2
Name: Day, Length: 100, dtype: int32

#### **6. Price, Quantity 사용해서 매출액 변수 생성**

In [ ]:
df.shape

(100, 21)

In [ ]:
df['TotalAmount'] = df['Price'] * df['Quantity']

In [ ]:
df.loc[:, ['Price', 'Quantity', 'TotalAmount']]

    Price  Quantity  TotalAmount
0      20         4           80
1      50         1           50
2      20         4           80
3      60         4          240
4     150         2          300
..    ...       ...          ...
95     80         1           80
96    500         2         1000
97     80         3          240
98     60         2          120
99     20         1           20

[100 rows x 3 columns]

In [ ]:
df.shape

(100, 21)

#### **7. 성별에 따라 가장 많이 구매하는 Product**

In [ ]:
df.loc[:, ['Gender', 'Product']]

    Gender     Product
0     Male     T-Shirt
1   Female       Jeans
2     Male     T-Shirt
3     Male    Backpack
4     Male  Headphones
..     ...         ...
95  Female    Sneakers
96  Female       Phone
97  Female    Sneakers
98  Female    Backpack
99    Male     T-Shirt

[100 rows x 2 columns]

In [ ]:
counts = df.groupby(['Gender', 'Product']).size()
most_buy = counts.groupby(level=0).idxmax()

for gender, (_, product) in most_buy.items():
    print(f"{gender}가 가장 많이 구매한 상품: {product}")

Female가 가장 많이 구매한 상품: Sneakers
Male가 가장 많이 구매한 상품: Backpack

#### **8. 연령대별로 가장 많이 쓰는 PaymentMethod**

In [ ]:
df.loc[:, 'PaymentMethod']

0            PayPal
1          KakaoPay
2       Credit Card
3     Bank Transfer
4     Bank Transfer
          ...
95    Bank Transfer
96    Bank Transfer
97      Credit Card
98         KakaoPay
99      Credit Card
Name: PaymentMethod, Length: 100, dtype: object

In [ ]:
counts = df.groupby(['AgeGroup', 'PaymentMethod']).size()
most_payment = counts.groupby(level=0).idxmax()

for age_group, (_, method) in most_payment.items():
    print(f"{age_group} : {method}")

10대 : Credit Card
20대 : PayPal
30대 : Bank Transfer
40대 : Bank Transfer
50대 : Credit Card
60대 이상 : Credit Card

#### **9. 매출액 기준 임의로 세우고 상, 중, 하 변수 만들어보기**

In [ ]:
q1 = df['TotalAmount'].quantile(0.25)
q3 = df['TotalAmount'].quantile(0.75)

print(q1)
print(q3)

def sales_category(amount):
    if amount >= q3:
        return '상'
    elif amount <= q1:
        return '하'
    else:
        return '중'

df['SalesCategory'] = df['TotalAmount'].apply(sales_category)

80.0
525.0

In [ ]:
df.loc[:, ['TotalAmount', 'SalesCategory']]

    TotalAmount SalesCategory
0            80             하
1            50             하
2            80             하
3           240             중
4           300             중
..          ...           ...
95           80             하
96         1000             상
97          240             중
98          120             중
99           20             하

[100 rows x 2 columns]